-- ============================================================
-- B'SEDER — MySQL Schema v1
-- ============================================================
-- Charset: utf8mb4 supports full Unicode including Hebrew characters.
-- All timestamps use DATETIME(3) = millisecond precision UTC.
-- Soft deletes: rows are never physically deleted; deleted_at is set instead.
-- IDs: CHAR(36) UUIDs generated by the application (UUID() or crypto.randomUUID()).
-- ============================================================
SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ─────────────────────────────────────────────────────────────────────────────
-- SCHEMA MIGRATIONS
-- Tracks which migration scripts have been applied so we never run one twice.
-- Each migration file inserts its version string here on completion.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE schema_migrations (
  version    VARCHAR(64) NOT NULL,            -- e.g. "20260401_001_initial"
  applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- USERS
-- One row per registered account. Soft-deleted users are kept so their goals
-- and assignments remain queryable for audit and potential account recovery.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
  id                  CHAR(36)     NOT NULL,  -- UUID primary key
  email               VARCHAR(320) NOT NULL,  -- RFC 5321 max length; must be unique
  display_name        VARCHAR(100) NULL,      -- how the user wants to be addressed in the UI
  password_hash       VARCHAR(255) NULL,      -- bcrypt hash; NULL = OAuth-only account (no password)
  avatar_url          VARCHAR(500) NULL,      -- URL to profile photo (S3 / Cloudflare R2 / CDN)
  -- Subscription: cached here for fast reads on every request.
  -- The subscriptions table holds the full billing history; this field is
  -- updated whenever a subscription event comes in from Stripe.
  subscription_status ENUM('free','pro')      NOT NULL DEFAULT 'free',
  created_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at          DATETIME(3)  NULL,      -- soft delete: set when account is closed
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email  (email),
  KEY        idx_users_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- SUBSCRIPTIONS
-- Full billing history. One active row per user at most; prior rows are kept
-- for receipts and audit. Integrates with Stripe — store their IDs so we can
-- look up invoices, cancel, or reactivate directly via the Stripe API.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE subscriptions (
  id                     CHAR(36)    NOT NULL,
  user_id                CHAR(36)    NOT NULL,
  plan                   ENUM('free','pro')                                        NOT NULL,
  status                 ENUM('active','trialing','past_due','canceled','expired') NOT NULL,
  stripe_customer_id     VARCHAR(64) NULL,     -- Stripe cus_xxx — links user to Stripe customer
  stripe_subscription_id VARCHAR(64) NULL,     -- Stripe sub_xxx — the active subscription object
  trial_ends_at          DATETIME(3) NULL,     -- when the trial period ends (NULL = no trial)
  current_period_start   DATETIME(3) NULL,     -- start of the current billing cycle
  current_period_end     DATETIME(3) NULL,     -- end of the current billing cycle / next renewal
  canceled_at            DATETIME(3) NULL,     -- when the user canceled (subscription may run until period_end)
  created_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_subscriptions_user   (user_id),
  KEY idx_subscriptions_stripe (stripe_subscription_id),
  CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- SESSIONS
-- Login sessions for authenticated users. token_hash stores a SHA-256 of the
-- actual session token so we never keep the raw token in the DB.
-- Used by NextAuth.js or a custom auth layer.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE sessions (
  id         CHAR(36)    NOT NULL,
  user_id    CHAR(36)    NOT NULL,
  token_hash CHAR(64)    NOT NULL,    -- SHA-256 hex of the bearer token
  expires_at DATETIME(3) NOT NULL,    -- session is invalid after this time
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sessions_token  (token_hash),
  KEY        idx_sessions_user    (user_id),
  KEY        idx_sessions_expires (expires_at),  -- used by the cleanup job
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- LOCATIONS
-- Shared location table used for zmanim (halachic times) calculation.
-- latitude + longitude + timezone together determine zmanim for any date.
--
-- Two kinds of rows live here:
--   is_preset = 1 → shipped with the app; read-only; created_by is NULL
--   is_preset = 0 → user-created custom location; created_by = that user's id
--
-- Only cities/communities with significant Jewish populations are preset.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE locations (
  id          CHAR(36)     NOT NULL,
  name        VARCHAR(255) NOT NULL,   -- display name, e.g. "Brooklyn, NY"
  latitude    DECIMAL(9,6) NOT NULL,   -- degrees N/S (negative = south)
  longitude   DECIMAL(9,6) NOT NULL,   -- degrees E/W (negative = west)
  timezone    VARCHAR(64)  NOT NULL,   -- IANA tz string, e.g. "America/New_York"
  is_preset   TINYINT(1)   NOT NULL DEFAULT 0,  -- 1 = system preset, 0 = user-created
  created_by  CHAR(36)     NULL,       -- NULL for presets; user id for custom locations
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at  DATETIME(3)  NULL,       -- soft-delete for user-created locations
  PRIMARY KEY (id),
  KEY idx_locations_preset     (is_preset),
  KEY idx_locations_created_by (created_by),
  CONSTRAINT fk_locations_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Preset seed: major Jewish population centers worldwide
-- Israel
INSERT INTO locations (id, name, latitude, longitude, timezone, is_preset) VALUES
  (UUID(), 'Jerusalem',            31.768959,  35.216209, 'Asia/Jerusalem',                      1),
  (UUID(), 'Bnei Brak',            32.084041,  34.833912, 'Asia/Jerusalem',                      1),
  (UUID(), 'Tel Aviv',             32.087719,  34.779560, 'Asia/Jerusalem',                      1),
  (UUID(), 'Haifa',                32.794044,  34.989571, 'Asia/Jerusalem',                      1),
  (UUID(), 'Beit Shemesh',         31.743290,  34.990650, 'Asia/Jerusalem',                      1),
  (UUID(), 'Modiin',               31.893780,  35.010150, 'Asia/Jerusalem',                      1),
  (UUID(), 'Raanana',              32.184330,  34.871540, 'Asia/Jerusalem',                      1),
-- United States — Northeast
  (UUID(), 'Brooklyn, NY',         40.650002, -73.949997, 'America/New_York',                    1),
  (UUID(), 'Manhattan, NY',        40.758896, -73.985130, 'America/New_York',                    1),
  (UUID(), 'Monsey, NY',           41.111290, -74.068680, 'America/New_York',                    1),
  (UUID(), 'Five Towns, NY',       40.627560, -73.730690, 'America/New_York',                    1),
  (UUID(), 'Lakewood, NJ',         40.095760, -74.217730, 'America/New_York',                    1),
  (UUID(), 'Teaneck, NJ',          40.891700, -74.012650, 'America/New_York',                    1),
  (UUID(), 'Baltimore, MD',        39.290385, -76.612190, 'America/New_York',                    1),
  (UUID(), 'Boston, MA',           42.360082, -71.058880, 'America/New_York',                    1),
  (UUID(), 'Philadelphia, PA',     39.952584, -75.165222, 'America/New_York',                    1),
-- United States — Midwest & South
  (UUID(), 'Chicago, IL',          41.878114, -87.629798, 'America/Chicago',                     1),
  (UUID(), 'Detroit, MI',          42.331427, -83.045754, 'America/Detroit',                     1),
  (UUID(), 'Cleveland, OH',        41.499320, -81.694360, 'America/New_York',                    1),
  (UUID(), 'Miami, FL',            25.774266, -80.193659, 'America/New_York',                    1),
  (UUID(), 'Aventura, FL',         25.956190, -80.139230, 'America/New_York',                    1),
  (UUID(), 'Houston, TX',          29.760427, -95.369804, 'America/Chicago',                     1),
  (UUID(), 'Dallas, TX',           32.776664, -96.796988, 'America/Chicago',                     1),
-- United States — West
  (UUID(), 'Los Angeles, CA',      34.052235,-118.243683, 'America/Los_Angeles',                 1),
  (UUID(), 'Palm Springs, CA',     33.830292,-116.545868, 'America/Los_Angeles',                 1),
  (UUID(), 'San Francisco, CA',    37.774929,-122.419418, 'America/Los_Angeles',                 1),
  (UUID(), 'Las Vegas, NV',        36.174969,-115.137341, 'America/Los_Angeles',                 1),
  (UUID(), 'Denver, CO',           39.739236,-104.984862, 'America/Denver',                      1),
  (UUID(), 'Scottsdale, AZ',       33.494170,-111.926048, 'America/Phoenix',                     1),
-- Canada
  (UUID(), 'Montreal, QC',         45.501689, -73.567256, 'America/Toronto',                     1),
  (UUID(), 'Toronto, ON',          43.651070, -79.347015, 'America/Toronto',                     1),
-- United Kingdom
  (UUID(), 'London',               51.507351,  -0.127758, 'Europe/London',                       1),
  (UUID(), 'Manchester',           53.480759,  -2.242631, 'Europe/London',                       1),
  (UUID(), 'Gateshead',            54.962780,  -1.603910, 'Europe/London',                       1),
-- Europe
  (UUID(), 'Antwerp',              51.219449,   4.402464, 'Europe/Brussels',                     1),
  (UUID(), 'Paris',                48.856613,   2.352222, 'Europe/Paris',                        1),
  (UUID(), 'Amsterdam',            52.370216,   4.895168, 'Europe/Amsterdam',                    1),
  (UUID(), 'Zurich',               47.376887,   8.541694, 'Europe/Zurich',                       1),
  (UUID(), 'Vienna',               48.208174,  16.373819, 'Europe/Vienna',                       1),
-- Latin America
  (UUID(), 'Buenos Aires',        -34.603722, -58.381592, 'America/Argentina/Buenos_Aires',      1),
  (UUID(), 'Sao Paulo',           -23.550520, -46.633308, 'America/Sao_Paulo',                   1),
  (UUID(), 'Mexico City',          19.432608, -99.133208, 'America/Mexico_City',                 1),
-- Australia & South Africa
  (UUID(), 'Melbourne',           -37.813628, 144.963058, 'Australia/Melbourne',                 1),
  (UUID(), 'Sydney',              -33.868820, 151.209290, 'Australia/Sydney',                    1),
  (UUID(), 'Johannesburg',        -26.195246,  28.034088, 'Africa/Johannesburg',                 1),
  (UUID(), 'Cape Town',           -33.924869,  18.424055, 'Africa/Johannesburg',                 1);

-- ─────────────────────────────────────────────────────────────────────────────
-- USER PREFERENCES
-- One row per user, created on signup with sensible defaults.
-- All calendar display settings live here rather than on the user row,
-- so the user row stays lean and auth-fast.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE user_preferences (
  user_id                        CHAR(36)   NOT NULL,           -- 1:1 with users
  location_id                    CHAR(36)   NULL,               -- FK to locations; NULL until user sets it
  time_format                    ENUM('12h','24h')           NOT NULL DEFAULT '12h',
  show_hebrew_dates              TINYINT(1) NOT NULL DEFAULT 1,  -- show Hebrew date below Gregorian
  week_starts_on                 TINYINT(1) NOT NULL DEFAULT 0,  -- 0 = Sunday, 1 = Monday
  default_view                   ENUM('month','week','day')  NOT NULL DEFAULT 'week',
  show_parsha                    TINYINT(1) NOT NULL DEFAULT 1,  -- show weekly Torah portion on Shabbos
  show_rosh_chodesh              TINYINT(1) NOT NULL DEFAULT 1,  -- highlight Rosh Chodesh days
  show_omer                      TINYINT(1) NOT NULL DEFAULT 1,  -- show Omer count during the Omer period
  show_modern_holidays           TINYINT(1) NOT NULL DEFAULT 0,  -- show Yom HaAtzmaut, Yom HaShoah, etc.
  show_outside_month_days        TINYINT(1) NOT NULL DEFAULT 1,  -- show faded days from adjacent months
  havdalah_opinion               ENUM('tzeit-8_5','42','50','72') NOT NULL DEFAULT 'tzeit-8_5',
  -- tzeit-8_5 = nightfall at 8.5 degrees below horizon (Geonim / most common)
  -- 42/50/72 = fixed minutes after sunset (various Ashkenazic opinions)
  timeline_snap_mins             TINYINT    NOT NULL DEFAULT 15, -- drag-snap granularity: 5/15/30/60
  timeline_default_duration_mins SMALLINT   NOT NULL DEFAULT 30, -- default block length: 15/30/45/60/90/120
  updated_at                     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (user_id),
  CONSTRAINT fk_prefs_user     FOREIGN KEY (user_id)     REFERENCES users     (id) ON DELETE CASCADE,
  CONSTRAINT fk_prefs_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- TAGS
-- User-defined labels (e.g. "Torah", "Health", "Work") that can be attached
-- to any goal for filtering and grouping. Each user manages their own tag set.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE tags (
  id         CHAR(36)     NOT NULL,
  user_id    CHAR(36)     NOT NULL,
  name       VARCHAR(100) NOT NULL,   -- tag label, e.g. "Learning"
  color      CHAR(7)      NULL,       -- hex color string, e.g. "#3b82f6"
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3)  NULL,       -- soft delete
  PRIMARY KEY (id),
  UNIQUE KEY uq_tags_user_name (user_id, name),  -- no duplicate names per user
  CONSTRAINT fk_tags_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOALS
-- The core entity. A goal represents something the user wants to do on a
-- recurring (daily/weekly/monthly/yearly) or one-time basis.
--
-- Two fundamental types:
--   binary     = done / not done each period (e.g. "Go to minyan")
--   quantified = X units per period (e.g. "Learn 10 pages/week")
--
-- Parent-child hierarchy: a goal can have a parent_goal_id pointing to another
-- goal in this same table. Example: "Run a marathon" (one-time, yearly) is the
-- parent of "Run 3x/week" (binary, weekly). Depth is unlimited but UI limits to 2.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goals (
  id                  CHAR(36)     NOT NULL,
  user_id             CHAR(36)     NOT NULL,
  parent_goal_id      CHAR(36)     NULL,      -- self-referencing FK; NULL = top-level goal

  title               VARCHAR(500) NOT NULL,
  cadence             ENUM('one-time','yearly','monthly','weekly','daily') NOT NULL,
  status              ENUM('ongoing','paused','done','archived')           NOT NULL DEFAULT 'ongoing',
  type                ENUM('binary','quantified')                          NOT NULL,

  -- Quantified goal fields
  target              INT          NULL,      -- obligation per period, e.g. 10 (pages/week); NULL for binary
  target_unit         VARCHAR(100) NULL,      -- unit label shown in the UI, e.g. "pages", "daf", "km"
  backlog             INT          NOT NULL DEFAULT 0,  -- accumulated missed units carried forward

  -- Planning behaviour
  no_getting_ahead    TINYINT(1)   NOT NULL DEFAULT 0,
  -- When 1: the user cannot plan more units in a period than target + backlog.
  -- Prevents assigning all 10 pages on Monday even if the goal says spread across Thu+Fri.
  if_unfinished       ENUM('forgive','backlog','track-failure','kill-streak') NULL,
  -- forgive       = period closes clean; missed units disappear
  -- backlog       = missed units accumulate in the backlog field and carry forward
  -- track-failure = missed periods are counted as failures (streak broken)
  -- kill-streak   = one missed period ends the goal entirely
  preferred_month_day VARCHAR(10)  NULL,
  -- For monthly goals: where in the month to auto-place.
  -- Values: "first", "last", or a number "1" through "31"
  lock_in_days        TINYINT(1)   NOT NULL DEFAULT 0,
  -- When 1: the goal cannot be dragged to a different day. Fixed to its scheduled day(s).
  adhoc               TINYINT(1)   NOT NULL DEFAULT 0,
  -- When 1: created via the quick "+ Add task" input. Does not appear in the goal tray.

  -- Halachic time window (daily goals only)
  starts_at           VARCHAR(100) NULL,      -- zmanim period key after which the goal becomes active, e.g. "Netz HaChama"
  expires_at          VARCHAR(100) NULL,      -- zmanim period key after which the goal is dimmed, e.g. "Chatzot"

  -- Lifecycle dates
  start_date          DATE         NULL,      -- first day this goal counts; NULL = counts from creation
  end_date            DATE         NULL,      -- last day this goal counts (recurring); NULL = no end
  due_date            DATE         NULL,      -- hard deadline for one-time goals
  end_after_periods   INT          NULL,      -- alternative end condition: stop after N completed periods

  -- Audit timestamps
  created_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  completed_at        DATETIME(3)  NULL,      -- set when status changes to 'done'
  paused_at           DATETIME(3)  NULL,      -- set when status changes to 'paused'
  archived_at         DATETIME(3)  NULL,      -- set when status changes to 'archived'
  deleted_at          DATETIME(3)  NULL,      -- soft delete

  PRIMARY KEY (id),
  KEY idx_goals_user    (user_id),
  KEY idx_goals_parent  (parent_goal_id),
  KEY idx_goals_cadence (cadence),
  KEY idx_goals_status  (status),
  KEY idx_goals_deleted (deleted_at),
  CONSTRAINT fk_goals_user   FOREIGN KEY (user_id)        REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_goals_parent FOREIGN KEY (parent_goal_id) REFERENCES goals (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOAL ACTIVE DAYS
-- Which days of the week a weekly goal is active on.
-- Replaces the activeDays: string[] array that currently lives on the Goal object.
-- One row per (goal, day) pair. The composite primary key enforces uniqueness.
--
-- day_of_week integer mapping: 0=Sun 1=Mon 2=Tue 3=Wed 4=Thu 5=Fri 6=Sat
-- Example: a goal active on Thu+Fri has two rows: (goal_id, 4) and (goal_id, 5)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goal_active_days (
  goal_id     CHAR(36) NOT NULL,
  day_of_week TINYINT  NOT NULL,  -- 0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat
  PRIMARY KEY (goal_id, day_of_week),
  CONSTRAINT fk_active_days_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOAL EXCLUSIONS
-- Jewish holidays on which a goal does NOT count toward its obligation.
-- Stored as individual holiday keys (e.g. "Yom_Kippur", "Chol_HaMoed_Pesach").
-- When a user selects a category like "Yom Tov", the app expands it to all
-- individual keys in that category before writing here. This keeps queries simple.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goal_exclusions (
  goal_id     CHAR(36)     NOT NULL,
  holiday_key VARCHAR(100) NOT NULL,  -- matches keys in HOLIDAY_GROUPS (holiday-catalog.ts)
  PRIMARY KEY (goal_id, holiday_key),
  CONSTRAINT fk_exclusions_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOAL TAGS  (junction table)
-- Many-to-many: a goal can have many tags; a tag can be on many goals.
-- Deleting a goal removes all its tag associations. Deleting a tag does the same.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goal_tags (
  goal_id CHAR(36) NOT NULL,
  tag_id  CHAR(36) NOT NULL,
  PRIMARY KEY (goal_id, tag_id),
  CONSTRAINT fk_goal_tags_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE,
  CONSTRAINT fk_goal_tags_tag  FOREIGN KEY (tag_id)  REFERENCES tags  (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOAL MILESTONES
-- Named checkpoints on one-time / project goals. Cosmetic only — checking one
-- off does not change goal.target or progress math. They are visual markers on
-- the progress bar (e.g. "Finish Mesechta Brachos" at page 64 of 192).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goal_milestones (
  id            CHAR(36)     NOT NULL,
  goal_id       CHAR(36)     NOT NULL,
  label         VARCHAR(500) NOT NULL,    -- milestone name shown in the UI
  marker_amount INT          NULL,        -- unit count where this milestone sits on the bar
  sort_order    SMALLINT     NOT NULL DEFAULT 0,  -- user-controlled order within the goal
  completed_at  DATETIME(3)  NULL,        -- when the user checked it off; NULL = not done
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at    DATETIME(3)  NULL,
  PRIMARY KEY (id),
  KEY idx_milestones_goal (goal_id),
  CONSTRAINT fk_milestones_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOAL PERIOD LEDGER
-- One row per goal per period. Written when a period opens (or on first
-- assignment within a period) and updated as the period progresses.
-- On period close: backlog_out = MAX(0, target_amount - completed_amount)
-- Next period: backlog_in = prior period's backlog_out.
--
-- This is the clean solution to the backlog/rollover problem. Instead of
-- re-scanning all history on every render, we materialize each period's
-- numbers here.
--
-- period_key format:
--   weekly  => "2026-03-22" (ISO date of the Sunday starting that week)
--   monthly => "2026-03"
--   yearly  => "2026"
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goal_periods (
  id               CHAR(36)    NOT NULL,
  goal_id          CHAR(36)    NOT NULL,
  period_key       VARCHAR(20) NOT NULL,  -- identifies the period (see format above)
  target_amount    INT         NOT NULL,  -- effective obligation = goal.target + backlog_in
  planned_amount   INT         NOT NULL DEFAULT 0,  -- how many units have been scheduled (assigned)
  completed_amount INT         NOT NULL DEFAULT 0,  -- how many units have been marked done
  backlog_in       INT         NOT NULL DEFAULT 0,  -- shortfall carried in from the prior period
  backlog_out      INT         NOT NULL DEFAULT 0,  -- shortfall to carry into the next period (set on close)
  period_ended_at  DATETIME(3) NULL,      -- NULL = period is still open; set when period closes
  created_at       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_goal_period (goal_id, period_key),
  CONSTRAINT fk_periods_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- GOAL STATUS HISTORY  (append-only audit log)
-- Every time a goal's status changes (ongoing => paused, paused => done, etc.),
-- a row is inserted here. Rows are NEVER updated or deleted.
-- Enables: "when did I pause this?", streak calculation, failure rate reports.
-- from_status is NULL only for the initial 'ongoing' creation event.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE goal_status_history (
  id          CHAR(36)    NOT NULL,
  goal_id     CHAR(36)    NOT NULL,
  from_status ENUM('ongoing','paused','done','archived') NULL,   -- NULL = this is the creation event
  to_status   ENUM('ongoing','paused','done','archived') NOT NULL,
  changed_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  note        TEXT        NULL,  -- optional user-written reason for the change
  PRIMARY KEY (id),
  KEY idx_status_history_goal (goal_id),
  CONSTRAINT fk_status_history_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- ASSIGNMENTS
-- The planning and completion record for a single goal on a single day.
-- An assignment is created when a user drags a goal to a day, or when a
-- recurring goal is explicitly scheduled (as opposed to the virtual "auto-show").
--
-- Key distinction: target_amount vs actual_amount
--   target_amount = how many units the user PLANNED for this session (e.g. 5 pages)
--   actual_amount = how many units the user ACTUALLY completed (entered at check-off)
--   These start equal; actual_amount can be less if the user did fewer than planned.
--
-- Auto-show suppression fields:
--   replaced_auto_date = if this assignment replaced a preferred-day auto-show,
--                        this is that preferred day's ISO date. Used to suppress
--                        the ghost auto-show from reappearing on that day.
--   skipped = 1 means this is a suppression record only — it renders nothing.
--             Created when deleting a moved assignment to keep the source day suppressed.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE assignments (
  id                 CHAR(36)    NOT NULL,
  goal_id            CHAR(36)    NOT NULL,
  user_id            CHAR(36)    NOT NULL,  -- denormalized from goal for fast per-user queries
  date               DATE        NOT NULL,  -- the calendar day this assignment belongs to
  period_key         VARCHAR(20) NULL,      -- origin period; preserved when the assignment is moved to another day

  -- Planning
  target_amount      INT         NULL,      -- units planned for this session; NULL = binary (done/not done)
  scheduled_time     TIME        NULL,      -- HH:MM placement on the day timeline (optional)
  duration_mins      SMALLINT    NULL,      -- block length on the timeline in minutes

  -- Completion
  completed          TINYINT(1)  NOT NULL DEFAULT 0,   -- 0 = not done, 1 = done
  completed_at       DATETIME(3) NULL,      -- timestamp of when the user checked it off
  actual_amount      INT         NULL,      -- units actually completed (may differ from target_amount)

  -- Auto-show lifecycle
  replaced_auto_date DATE        NULL,      -- preferred-day ISO date that this assignment replaced
  skipped            TINYINT(1)  NOT NULL DEFAULT 0,
  -- When 1: this is a suppression-only record. No goal item is rendered.
  -- The row's date field points to the preferred day being suppressed.

  -- Audit
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at         DATETIME(3) NULL,      -- soft delete (restores the auto-show on the calendar)

  PRIMARY KEY (id),
  KEY idx_assignments_goal      (goal_id),
  KEY idx_assignments_user_date (user_id, date),           -- primary query: "what's on my calendar today?"
  KEY idx_assignments_period    (goal_id, period_key),     -- period progress aggregation
  KEY idx_assignments_deleted   (deleted_at),
  CONSTRAINT fk_assignments_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE,
  CONSTRAINT fk_assignments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- OMER COMPLETIONS
-- Simple record of which days the user counted the Omer.
-- No content beyond the date — the Omer count number is always computed
-- from the date (day N of the Omer = days since 2nd night of Pesach).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE omer_completions (
  user_id        CHAR(36)    NOT NULL,
  completed_date DATE        NOT NULL,   -- the Gregorian date the user counted on
  counted_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),  -- exact time they tapped "count"
  PRIMARY KEY (user_id, completed_date),
  CONSTRAINT fk_omer_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- USER GOAL ORDER
-- Persists the user's drag-and-drop sort order of goals in the sidebar tray.
-- One row per (user, goal) pair. sort_order is a plain integer; to reorder,
-- update all affected rows (or use a float-based fractional indexing strategy).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE user_goal_order (
  user_id    CHAR(36) NOT NULL,
  goal_id    CHAR(36) NOT NULL,
  sort_order INT      NOT NULL DEFAULT 0,  -- lower = higher in the list
  PRIMARY KEY (user_id, goal_id),
  KEY idx_goal_order_sort (user_id, sort_order),
  CONSTRAINT fk_goal_order_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_goal_order_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
